### ISSUE TITLE
`count` zero in code scan report

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#138]
The `count` attribute in the code scan report [codescan-checkmarx-one-yellow-finding-result-beautified.json](https://github.com/Daimler/sechub/blob/develop/sechub-other/examples/sechub-reports/codescan-checkmarx-one-yellow-finding-result-beautified.json) is zero, even though there are several findings in the report. It would be nice to have a correct finding count in the code scan report.

**Comment by de-jcup** [comment]
We are thinking about adding optitional parts like license problems - see #151  . Maybe we should either
- remove the count option at all
- move the count to findings
- make the count value count all parts
- ...

**Comment by Jeeppler** [comment]
I opinion we should keep a finding count, since a human being can read the scan report and see how many findings are in the report. Additionally, not having a count means that every client has to implement there own `count` functionality.  

We should probably have a total count of all findings (code scan, infra scan, dynamic webapp scans). In addition, we could have a separate count for each part. The advantage of having a count for each part would be, that we know upfront in which part we have findings and can treat the parts with no findings differently while working with the report.
