### ISSUE TITLE
Fix typos and missing new lines in mail text for admins

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#164]
## Current situation
> as a new administrator of sechub for environment (base url):https://xx.yy.zz Email adress of new colleague is:xx.xx@example.comDon't forget: Colleague email adress should be added to NPM (email administrators) as well.

## Wanted

> as a new administrator of sechub for environment (base url):https://xx.yy.zz 
> 
> Email adress of new colleague is:xx.xx@example.com
> Don't forget: Colleague email adress should be added to NPM (email administrators) as well.

**Comment by de-jcup** [comment]
Found another one:

> User xxxleft **hte** group of sechub administrators.
> 
> She/He will be no longer admin for environment (base url):https://sechub-xxx.example.com
> Email adress of old colleague was:xx.yy@example.comDon't forget: Colleague email adress should be removed from NPM (email administrators) as well.
>

**Comment by sven-dmlr** [comment]
Created branch feature-36-api-token-as-env-variable 

- Additionally added a warning message when using -apitoken instead of the environment variable.
- added possibilty to pass SecHub UserID as environment variable SECHUB_USERID
- added possibilty to pass SecHub Server String as environment variable SECHUB_SERVER

**Comment by sven-dmlr** [comment]
- tweaked email texts and subjects
- added environment url where possible
- spell corrections
- tested+verified locally

**Comment by sven-dmlr** [comment]
github actions Go build fails due to #208 
Should be gone when PR #36 is merged.

**Comment by sven-dmlr** [comment]
fixed by https://github.com/Daimler/sechub/pull/245
