### ISSUE TITLE
Wrong validation of username length

### ISSUE THREAD

**Issue by sven-dmlr** [Daimler/sechub#180]
Having a project id with 4 characters ("gsep") and a userid with 6 characters ("pid1234"):

When assigning the user to the project, I get this error:
```
[EXECUTE] AssignUserToProjectAction-1581687652523
ERROR:
status code::406 NOT_ACCEPTABLE, text:,body:
{"status":406,"error":"Not Acceptable","message":"User is is not valid. Minimum size is 5 but was 4","details":[],"timeStamp":"Fri Feb 14 13:41:10 UTC 2020"}
assigned pid1234 to project gsep
[DONE]
```
Even though the username length is correct.

I created a project "gsep-123" and tested the same: now the user assignment worked.

So it seems
- the length of the _project id_ is evaluated instead of the length of the _user id_.
- and the message "assigned pid1234 to project gsep" is misleading because the user was _not_ assigned. (Maybe this should be split into a separate issue.)

**Comment by de-jcup** [comment]
There exist also an typo (" is is"). will be fixed inside this issue as well.
