### ISSUE TITLE
Inspect non breaking github actions for SecHubServer

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#208]
https://github.com/Daimler/sechub/runs/523354878 did show some obscure go build failures, but not that there were 6 java test failures in formerly build SecHub Server (which was green!)

**Comment by sven-dmlr** [comment]
@de-jcup 
The proposed step didn't help.

BUT: I've found out (after much testing around) that all goes smooth when we move the server build step behind the CLI build step. It's kind of weird, but now the github builds are green again (see https://github.com/Daimler/sechub/runs/549199764?check_suite_focus=true).

Shall we pass it into the develop branch along with "feature-36-api-token-as-env-variable"?
PR will come tomorrow.
Or shall I prepare a separate PR only with the build fix?

**Comment by sven-dmlr** [comment]
Issue is fixed by PR #211
