### ISSUE TITLE
Implement reasonable default exclude patterns

### ISSUE THREAD

**Issue by sven-dmlr** [Daimler/sechub#227]
Code Scan: Enable lazy usage of client:
If no excludes are defined in the sechub.json config file, then use reasonable defaults.
( see https://daimler.github.io/sechub/latest/sechub-client.html#example-upload-folders-with-excludes )

Benefits:
- save bandwidth and disk space on server
- speed up scan

Open discussion:
Which exclude patterns should be added (source code scan)?
```
- Archives: **/*.7z **/*.bz2 **/*.gz **/*.rar **/*.tar **/*.tgz **/*.zip
- Binary image files: **/*.bin **/*.cue **/*.iso **/*.mdf **/*.vcd
- Build artifacts: **/*.o
- Documents: **/*.doc **/*.docx **/*.eps **/*.odc **/*.odp **/*.odt **/*.rtf **/*.pdf **/*.pps **/*.ppt **/*.pptx **/*.ps **/*.svg **/*.xls **/*.xlsx
- Executables: **/*.com **/*.exe
- Fonts: *.fnt *.otf *.ttf
- Images: **/*.bmp **/*.gif **/*.ico **/*.jpeg **/*.jpg **/*.png **/*.svg **/*.tif **/*.tiff **/*.xcf
- Libraries: **/*.a **/*.dll **/*.jar **/*.so
- OS packages: **/*.apk **/*.app **/*.cab **/*.deb **/*.rpm **/*.dmg
- Sound/Videos: **/*.aif **/*.avi **/*.flac **/*.flv **/*.gifv **/*.ogg **/*.ogv **/*.mid **/*.mkv **/*.mov **/*.mp2 **/*.mp3 **/*.mp4 **/*.mpa **/*.mpeg **/*.mpg **/*.vob **/*.wav **/*.wma **/*.wmv **/*.webm
- Text files: **/*.md **/*.adoc **/*.asciidoc **/*.log **/*.plantuml **/*.puml **/*.tex **/*.txt **/*.latex **/*.vcf
```

**Comment by sven-dmlr** [comment]
Idea: use whitelist (allowed file extension) instead of exclude patterns.

**Comment by Jeeppler** [comment]
I think the folder */test/* can be excluded by default.

**Comment by de-jcup** [comment]
Hmm.. I would appreciate more `**/src/test/**` because its the maven/gradle standard - and also prevents to have accidently filtered unwanted parts - e.g. `com.example.myserver.test.NetworkConnectionStable.java` will not be filtered...

**Comment by sven-dmlr** [comment]
> Hmm.. I would appreciate more `**/src/test/**` because its the maven/gradle standard - and also prevents to have accidently filtered unwanted parts - e.g. `com.example.myserver.test.NetworkConnectionStable.java` will not be filtered...

When the filter is `**/test/**`, your example would not be filtered because of the directory separators `/`. I see no unwanted effects with this pattern.

Will add `"**/test/**", "**/.git/**"` initially.
