### ISSUE TITLE
SecHub client remove false positives

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#241]
## Situation
With implementation of #239  it is possible to remove false positives by REST API.

But for users we need a more convenient way. Because we have currently no Web UI we must integrate this into our sechub client.

### General
We reuse credentials and project data already defined for scans etc.! So we assume that user, apitoken, project and also server are defined (either by environment variables or as parameters) and do not show them in the example calls!

### Variant 1  - use json file with false positive list
A user creates a JSON file and describes there wrong false positives. See [example1.json](https://github.com/Daimler/sechub/blob/develop/sechub-doc/src/docs/asciidoc/documents/shared/concepts/false-positive-handling/false-positive-REST-API-content-example1.json)
```
sechub 
 -file ${pathToJSONFileContainingFalsePositiveList}
  removeFalsePositives
```
This is the simplest approach: Same as doing rest operation directly (but with some more convenience, validation and no dependencies to other tools - e.g curl).
But... here the user will have no feedback, if numbers were correct etc.

### Variant 2 - fetch false positive configuration for project and mark findings
For this #240  must be implemented before!
```
sechub 
  unmarkFalsePositives
```
The client will load JSON configuration file from server and start showing most severe parts (first critical, medium than low)

Pseudo output example:
```
sechub -project myproject unmarkFalsePositives
---------------------------------------------------------------------------
1: Absolute Path Traversal, severity: MEDIUM
java/com/daimler/sechub/docgen/AsciidocGenerator.java, line:28, column:35:
      public static void main(String[] args) throws Exception {
---------------------------------------------------------------------------
Do you want to remove this false positive? (y/Y -yes, n/N - no, s/S - skip following, c/C - cancel)
```
If user press 
- "c" operation will be complete canceled - exit 0
- "n" will show and ask for next finding, or if last ... see s/S-skip description
- "y" will mark internally and show and ask for next finding, or if last ... see s/S-skip description
- "s" will no longer ask but do
  - exit 0 when nothing was marked
  - show up a summary - e.g. "Will unmark following (n) findings:"
  - ask "Are you really sure?" and if answered with "y" create json content and calls REST API (as 
   done for variant1)

## Tasks
- [ ] implement variant 1 + upgrade client help + upgrade client documentation
- [ ] implement variant 2 + upgrade client help + upgrade client documentation

**Comment by sven-dmlr** [comment]
In unmarkFalsePositives it is impossible to display line/column in source code because it is not provided in getFalsePositives json file.

@de-jcup : if line/column of source code is stored on the SecHub server: Please provide them in getFalsePositives so it can be displayed e.g. in unmarkFalsePositives like proposed here in the feature decription.

**Comment by de-jcup** [comment]
We will switch namings:

- unmarkFalsePositives
- removeFalsePositives

to
- unmarkFalsePositives
- interactiveUnmarkFalsePositives
