### ISSUE TITLE
SecHub client can download false-positive data as JSON file

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#242]
## Situation
With implementation of #240 it is possible to fetch information about false positives by REST API.

But for users we need a more convenient way. Because we have currently no Web UI we must integrate this into our sechub client.

### General
We reuse credentials and project data already defined for scans etc.! So we assume that user, apitoken, project and also server are defined (either by environment variables or as parameters) and do not show them in the example calls!

### Variant 1 - download false positive data to file
For this #240  must be implemented before!
```
sechub 
  getFalsePositives
```
The client will load JSON data of marked falsse positives from server by REST API and store the content as a JSON file ("false-positives-${projectId}.json")

## Tasks
- [ ] implement variant 1 + upgrade client help + upgrade client documentation

**Comment by sven-dmlr** [comment]
feature is implemented
(still open: integration tests of false-positives handling with sechub client)
