### ISSUE TITLE
Client: zip file grows infinitely when using "." as folder

### ISSUE THREAD

**Issue by sven-dmlr** [Daimler/sechub#258]
How to reproduce:
sechub.json
```
{
    "apiVersion" : "1.0" ,
    "project" : "sechub" ,
    "codeScan": {
        "fileSystem": {
            "folders": [ "." ]
        }
    }
}
```
Running the SecHub client (needed to interrupt with ctrl+C):
```
> sechub -server https://sechub.example.com scan 
 _____           _   _       _     
/  ___|         | | | |     | |    
\ `--.  ___  ___| |_| |_   _| |__  
 `--. \/ _ \/ __|  _  | | | | '_ \ 
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.0.0-70970d3-dirty-latest
- Creating new sechub job
2020/06/17 10:02:14 Zipping folder: /home/developer/git/tmp
^C
```
Looking into the directory:
```
> ls -l
-rw-rw-r-- 1 developer developer   4439592 Jun 17 10:00 file.txt
-rw-rw-r-- 1 developer developer       147 Jun 17 10:02 sechub.json
-rw-rw-r-- 1 developer developer 450400832 Jun 17 10:02 sourcecode-febbb02a-839d-4774-aee9-949ed4caf3ae.zip
```
**Bug**: Although it is no good idea to use "." as folder, it should be detected that the zip file is inside the defined scan folder.

---
<sup>Sven Dolderer <sven.dolderer@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
Hmm.. so the existing check does not work correctly. Must be done.

**Comment by hoftill** [comment]
> **Bug**: Although it is no good idea to use "." as folder, it should be detected that the zip file is inside the defined scan folder.

Is there a specific reason why this is a bad idea? In my opinion, it makes sense because you can then add the sechub.json into the repository as well. (Which again makes sense, because it (only) differs between repositories.)

---
<sup>Till Hoffmann <[till.hoffmann@daimler.com](mailto:till.hoffmann@daimler.com)> Daimler TSS GmbH. [Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by sven-dmlr** [comment]
The comment was not meant that you should not add sechub.json into your git repository.
It was meant, that in most cases you don't need to scan '.' with sechub because the source code usually is only in specific source-code subdirectories. If you configure these in sechub.json, then the sechub client does not have to scan all files in all subdirectories, but only the relevant ones. This can improve performance for big projects.

**Comment by hoftill** [comment]
I see. But then the files in "." wouldn't be scanned. For example, if I had an issue in a graddle build file.
Still, I get your point that this might be not the case for bigger projects.
Thank you for clarification.
