### ISSUE TITLE
sechub client on linux doesn't recognize apitoken env-variable

### ISSUE THREAD

**Issue by hoftill** [Daimler/sechub#277]
There seems to be an issue with the apitoken argument, which should be passed as an environment variable to the client.
I created an environment variable with the token, so that running `./sechub -apitoken $SECHUB_APITOKEN scan` works fine (despite a warning).

- Running `./sechub -apitoken scan` returns the same warning plus
`sechub action not set`
Expected: According to https://github.com/Daimler/sechub/blob/4df05b108849774d195ccf1b7d2b9872df21849a/sechub-cli/src/daimler.com/sechub/cli/config.go#L93 this should read from the environment variable.
- Running `./sechub scan` returns
`api token missing!`
Expected: As stated in https://daimler.github.io/sechub/latest/sechub-client.html#scan, this should work.

Could you please look into this?

> Note: I'm working on Ubuntu 18.04

Till Hoffmann <[till.hoffmann@daimler.com](mailto:till.hoffmann@daimler.com)> Daimler AG on behalf of Daimler TSS GmbH.

[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by sven-dmlr** [comment]
Hi Till,
- When using `sechub -apitoken scan`, then "scan" is considered to be the value of the apitoken. This results in the error message you see.
- Your second attempt should work as documented: `sechub scan`. When previously the env variable has been defined (`export SECHUB_APITOKEN=yoursecretapitoken`) This way we do all out testing.

---
<sup>Sven Dolderer <sven.dolderer@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by hoftill** [comment]
Hi Sven,
Thanks for clarification - I didn't `export` the variable definition.
