### ISSUE TITLE
Mixed programming languages lead to only one being analyzed

### ISSUE THREAD

**Issue by hoftill** [Daimler/sechub#280]
Hello sechub-team,
we have a project, where both Go and Kotlin (and .html) files are used (subfolder/-projects). When running the code analysis, only one language is analyzed.
Can this be adjusted, or is it necessary to run the client several times (once for each language) and only for one part of the project at a time?

---
<sup>Till Hoffmann <[till.hoffmann@daimler.com](mailto:till.hoffmann@daimler.com)> Daimler AG on behalf of Daimler TSS GmbH. [Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by sven-dmlr** [comment]
The behavior you observed has nothing to do with SecHub.
SecHub always passes all uploaded sources to the scan backend(s).

So the findings completely depend on the quality of the scan backends.
Closing this issue.

---
<sup>Sven Dolderer <sven.dolderer@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>
