### ISSUE TITLE
Client: Improvements for false-positives handling

### ISSUE THREAD

**Issue by sven-dmlr** [Daimler/sechub#285]
This should be implemented to complete #238 #241 
- When reading reports/false-positives list from server: sort items by severity,ID
- In markFalsePositives/unmarkFalsePositives sum up the changes and add confirmation "Are you really sure?"
- Documentation of new features (use proper options - new: unmarkFalsePositves/markFalsePositves/interactiveMarkFalsePositves/interactiveUnmarkFalsePositves)
- increase test coverage of Go tests

---
<sup>Sven Dolderer <sven.dolderer@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
Standard false positive commands are already documented in #323

**Comment by sven-dmlr** [comment]
Will close this issue, because:

_When reading reports/false-positives list from server: sort items by severity,ID_
-> currently they come already sorted - open a new issued once they come unsorted from the server.

_In markFalsePositives/unmarkFalsePositives sum up the changes and add confirmation "Are you really sure?"_
-> Postponing, because this is not essential (open a new issue if needed)

_Documentation of new features (use proper options - new: unmarkFalsePositves/markFalsePositves/interactiveMarkFalsePositves/interactiveUnmarkFalsePositves)_
-> already done: see https://daimler.github.io/sechub/latest/sechub-client.html

_increase test coverage of Go tests_
-> already done along with the other changes
