### ISSUE TITLE
Add SecHub Client Section to Quickstart Guide

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#305]
Add a section to the quickstart guide explaining how to use the sechub client to do a SAST scan.

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
Add a basic visualization of the architecture (SecHub Server) <-> (SecHub Client) as well.

**Comment by manu-ki** [comment]
- Setup sechub server locally -> Getting Started Guide: https://daimler.github.io/sechub/latest/sechub-quickstart-guide.html
- how to make a local test scan
---
<sup>Manuela Kirchner <manuela.kirchner@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>
