### ISSUE TITLE
Provide a simple java client as library - so suitable for plugin development

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#324]
For developing IDE plugins being java based (e.g. Eclipse, IntelliJ) , we need a simple to use java client library.

- The client will NOT be a full replacement for `sechub-cli`, but contains only some essential access methods.
- It shall be as small as possible, so will NOT have a dependency to `sechub-shared-kernel`. We accept to have some duplicates here
- Future sight: When we provide OpenAPI REST descriptions we could generate acces parts. But currently we just code some access parts manually.

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
In case the [Web UI](https://github.com/Daimler/sechub/issues/11) will be a separate application we would need the Java client library to be able to interact with the main SecHub server's REST API. Therefore, all necessary use cases have to be implemented in the client library.

**Comment by Jeeppler** [comment]
A client library written in Java could be transpiled to TypeScript/JavaScript using [JSweet](http://www.jsweet.org/). This could be helpful for writing an [Extension](https://code.visualstudio.com/api) (plugin) for VS Code.
