### ISSUE TITLE
Add SPDX License Header to Analyzer-Cli Test Files

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#327]
Add SPDX license headers to all test files in the Analyzer-Cli project.

**Comment by de-jcup** [comment]
@Jeeppler : please look at ./apply-headers.sh in root folder. This does automatically appy spdx to our "normal" soruce files. It also describes some problem solutions/mitigations - e.g. for bash files (we do NOT add spdx headers on first line there...).
