### ISSUE TITLE
Not all parameters documented for create-project

### ISSUE THREAD

**Issue by sven-dmlr** [Daimler/sechub#332]
Please make sure that all parameters are documented in https://daimler.github.io/sechub/latest/sechub-restapi.html#admin-creates-a-project 

Missing fields:
- project owner
- project description

---
<sup>Sven Dolderer <sven.dolderer@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
@sven-dmlr is the owner mandatory?

**Comment by Jeeppler** [comment]
The project meta data feature is not documented either #425.

**Comment by sven-dmlr** [comment]
> @sven-dmlr is the owner mandatory?

Yes
