### ISSUE TITLE
Pattern For Report Output File Name

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#333]
Currently, the output name of a scan has the pattern `sechub_report_<jobUUID>`. This is helpful in case you do only a few scans. However, once you do several scans, it becomes hard to identify which scan was triggered at what time or for what project/scan configuration. In addition, the operating system sorts the sechub reports according to the jobUUID, which is not helpful.

It would be nice to be able to provide a custom pattern. For example, `sechub_report_my_project_<date>_<jobUUID>`. The client will then fill in the values for `<date>` and `<jobUUID>` for every scan.

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
Default should be as is - but users should be able to customizable outputfile as described above. Good idea!

**Comment by sven-dmlr** [comment]
One part is already implemented:
The project name is meanwhile included in the file name. See #347 

Implementing the proposed features seems to me like adding a "golden handle".

Will implement at the client the ability to define a custom output file/path.
See -> #929

**Comment by sven-dmlr** [comment]
Closing this issue.
