### ISSUE TITLE
GoSec + PDS

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#362]
[GoSec](https://github.com/securego/gosec) is a static application security testing tool for the Go programming language. GoSec itself is written in Go.

GoSec is a good candidate to test the new Product Delegation Server (PDS).

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
GoSec supports SARIF.

**Comment by company-jcup** [comment]
We will create the PDS parts inside this repository which can start a PDS server with gosec "out-of-the-box"

```
sechub-pds-examples
           /gosec/
               config.json
               scan-with-gosec.sh
               README.md
               Dockerfile
               docker-run.sh  // does build + run a docker container 
                              // (downloads xyz version of sechub-pds,
                              // uses upper config and start script etc. out-of-the-box)
```

**Comment by Jeeppler** [comment]
For TLS rules one more step is required: https://github.com/securego/gosec#generate-tls-rule
