### ISSUE TITLE
Enhance OpenAPI file generation and java client source code

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#377]
## Situation
With #324 also #145 was done.

openapi3.yaml file is now generated automatically inside /sechub-doc/build/apispec by CI.

Also openapi generator for java is automatically called from CI and java classes are generated. 
This is done inside sechub-client-java/build.gralde.

But currently the generated java classes are
- not used by sechub client
- not inside src/gen/java but only at build folder
- contain strange classnames (jobuuid parameter is used for generation which is is odd)

Maybe it's also necessary to improve the openapi3 file generation to provide better java class names.

## Where can I see the problem?
`sechub-doc/build/api-spec/openapi3.yaml`:

contains for example: `/api/admin/jobs/cancel/131f7099-1aac-4e5b-8276-10defb0ad9b0:`
as a URL where parameter with job uuid is not recognized but used as URL literal instead

## Wanted
- OpenAPI generation must be improved, so class names are stable and contain no parameter names any longer
- Change build so openapi generator output is generated to src/gen/java instead  of build/generated
- Add src/gen/java to source folders of sechub-client-java gradle project
- Make java compile task dependent of openapi generation (so compile works when clean git clone)
- SecHubClient shall take advantage from generated classes and provide a stable API. We will always provide a wrapper method from sechub client to generated java classes - so if generator changes, our client library API will NOT change...

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
There are multiple restdoc tests where no correct path parameterization is done :+1: 

An example:
```
String profileId="profile-1";
...
post(https(PORT_USED).buildAdminCreatesProductExecutionProfile(profileId).
```
So at generation the pathes inside documentation (RESTDOC) does show up the example profile id and no parameter! Also this is problematic for openapi generation, because example is used for every call...

Must be fixed this way:
```
post(https(PORT_USED).buildAdminCreatesProductExecutionProfile(PROFILE_ID.pathElement()),profileId).
```

**Comment by de-jcup** [comment]
To have a "smooth" api (means names with dedicated meaning) we must give correct rest pathes for restdoc, which leads to correct operationIds which leads to correct generated java classes for rest client...

### Todos
- To provide this we simply reuse the `UseCaseDefinition` annotation and add a new field there - for example `apiName`

- So every usecase got a mandatory field which describes the apiName. 
(will create 57 compile errors at the moment, so its clear where we have to insert  api names...)

- Then we will change `RestDocPathFactory.createPath(...)` and use the apiName from the usecase definition (see `createIdentifier` method)
    - The default variant should no longer be added as" _default" inside created path.
Other variants should be still added in this way! E.g. `get_report_json`

- To ensure we got unique apiNames there should be either a junit test checking the uniqueness by
  reading annotated data and check for duplicates or we do simply check this inside restdoc factory.
  But a test would reduce time for builds because documentation only build when tests are green...

**Comment by Jeeppler** [comment]
There is some issue with the schema generation. See [#147](https://github.com/ePages-de/restdocs-api-spec/issues/147).

**Comment by Jeeppler** [comment]
There is currently no support for multipart uploads. See [#105](https://github.com/ePages-de/restdocs-api-spec/issues/105).

**Comment by Jeeppler** [comment]
The sources can be generated with `./gradlew :sechub-client-java:openApiGenerate`.

**Comment by Jeeppler** [comment]
`oneOf` and `anyOf` are supported in OpenAPI 3.0, but the OpenAPI generator still has some issues with it: 
https://stackoverflow.com/questions/62760156/how-to-use-openapi-oneof-property-with-openapi-generator-maven-plugin-when-gen

**Comment by Jeeppler** [comment]
Have a look on how to manipulate the OpenAPI 3 file to get rid of `oneOf`s: https://stackoverflow.com/questions/57116554/how-to-programatically-edit-a-swagger-yaml-file-in-java-to-add-a-request-paramet

Basically, either use [swagger-parser](https://github.com/swagger-api/swagger-parser) or [Jackson-Dataformat-Text/Yaml](https://github.com/FasterXML/jackson-dataformats-text/tree/2.13/yaml)

**Comment by Jeeppler** [comment]
We will generate the OpenAPI file as JSON and use get rid of `oneOf`'s use Groovy's JsonSlurper library: http://docs.groovy-lang.org/latest/html/gapi/groovy/json/JsonSlurper.html

**Comment by Jeeppler** [comment]
In the future it would be nice to be able to generate both JSON and YAML versions of the OpenAPI file in a single run: https://github.com/ePages-de/restdocs-api-spec/issues/176

**Comment by Jeeppler** [comment]
Splitted the issue into two. The follow up issue is #728.
