### ISSUE TITLE
Sereco support for SARIF

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#386]
We will provide SARIF inside Sereco ( see https://sarifweb.azurewebsites.net/) because it is supported by OASIS and becomes a standard of SAST report formats.

It will also help us to simplyfy PDS integration very much! Every product supporting SARIF will be very easy to integration when PDS integration in SecHub is full done.

**Comment by Jeeppler** [comment]
I think this issue is a duplicate of #364.

**Comment by 4w31ss3** [comment]
#575 addresses currently empty vulnerability description field.
