### ISSUE TITLE
Admin users can scan not existing projects

### ISSUE THREAD

**Issue by sven-dmlr** [Daimler/sechub#400]
When SecHub admin users start a scan, there is no check if the requested project exists.
Even worse: the whole scan is done including creation of the project in third-party tools.
(In this case, a Checkmarx license was wasted)

-> Please check and implement that in any case the project must exist before scanning is started

To reproduce: (project "phantasy" does not exist on SecHub server)
```
> cat sechub.json
{
  "apiVersion" : "1.0" ,
  "server"   : "https://sechub.example.org",
  "project"  : "phantasy",
  "codeScan": {
    "fileSystem": {
      "folders": ["src"]
    }
  }
}

> export SECHUB_USERID=my-admin-user ; export SECHUB_APITOKEN=.......

> sechub scan
 _____           _   _       _     
/  ___|         | | | |     | |    
\ `--.  ___  ___| |_| |_   _| |__  
 `--. \/ _ \/ __|  _  | | | | '_ \ 
/\__/ /  __/ (__| | | | |_| | |_) |
\____/ \___|\___\_| |_/\__,_|_.__/ Client Version 0.21.0

- Creating new sechub job
Zipping folder: src (/home/myuser/tmp/sechub/demo/src)- Uploading source zip file
- Approve sechub job
- Waiting for job 960103be-c80e-4b56-88ad-e30c7fde22e2 to be done
  ....
- Fetching result (format=json) for job 960103be-c80e-4b56-88ad-e30c7fde22e2
- SecHub report written to sechub_report_phantasy_960103be-c80e-4b56-88ad-e30c7fde22e2.json
  GREEN - no security vulnerabilities identified
```

---
<sup>Sven Dolderer <sven.dolderer@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by sven-dmlr** [comment]
Duplicate of #123

**Comment by de-jcup** [comment]
As mentioned in #123  this is currently a wanted behaviour.

But I see this is very confusing...

So we could do following:
- If admin account, check if there exists at least one ProjectAccess Entry for this project
- if not fail with (no access to any user or project does not exist)
- if at least one and admin role, give access
