### ISSUE TITLE
WebScan Introduce Wait Setting For Login Script

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#440]
At the time of writing, it is not possible to define a wait parameter for every step in a script which is used to login into a more complex website. Waiting for some time is important, as the page could take a while to load the entire Document Object Model (DOM). 

It should be possible to provide the wait parameter for every step in the form login script. The value of the `wait` parameter should be in milliseconds (ms).

An example on how the `wait` parameter could look like is shown below.
~~~
{
  "apiVersion": "1.0",
  "server": "https://sechub.example.com",
  "project": "sechub",
  "webScan": {
      "uris": ["https://target.example.org"],
      "login": {
            "url": "https://target.example.org/login",
            "form": {
                "script": [
                    {
                        "step": "username", 
                        "selector": "#username",
                        "value": "my_user",
                        "wait": 2000
                    },
                    {
                        "step": "password",
                        "selector": "#password",
                        "value": "top4xSecret!"
                    },
                    {
                        "step": "click",
                        "selector": "#loginButton"
                    }
                ]
            }
        }
  }
}
~~~

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
Would be nice to have a class `SechubTimeUnitData` which we could use in different json situations like:

```json
"wait": {
   "time" : 1,
   "unit" : "h"
}
```
So we would provide dedicated units "ms" , "s", "m" and "h" (and maybe "d" or full named "millseconds" ,...

So in example before this would be like:
```json
{
     "step": "username", 
     "selector": "#username",
     "value": "my_user",
     "wait": {
          "time" : 2000,
           "unit" : "milliseconds"
      }
 },
```

`SechubTimeUnitData` would have fields "time" and "unit" getters,setters but also an additional method `getTimeInMilliseconds()` which would automatically generate millesconds so easy to use ... (of course with @JSONignore annotation...)

Example:
"time:" 2, "unit":"seconds" --> getTimeInMilliseconds() returns 2000....

**Comment by Jeeppler** [comment]
Another option would be to use a wait action:

~~~
{
    "action": "username",
    "selector": "#example_login_userid",
    "value": "user2",
    "description": "The username is different from the email address"
},
{
   "action": "wait",
   "value" : "1000",
   "unit": "milleseconds"
},
~~~

The wait action would make it easy to see, if the wait happens before or after the action.

**Comment by de-jcup** [comment]
To clarify - this has been changed together with #572. 
At the end we did  agreed with each other to provide action nodes inside "actions" array inside JSON.
The "step" has been changed to "type". And there is now a type "wait" which provides the wanted feature.
(Implementation was done with #572)

We do now support following style:

```json
"actions": [
                {
                  "type" : "wait",
                  "value" : 3200,
                  "unit" : "milliseconds"
                }, {
                  "type" : "input",
                  "selector" : "#email_field",
                  "value" : "user@example.org",
                  "description" : "The user's email address."
                }, {
                  "type" : "password",
                  "selector" : "#example_login_pwd",
                  "value" : "pwd2"
                }, {
                  "type" : "click",
                  "selector" : "#example_login_login_button"
                }
                ]
            }
```
