### ISSUE TITLE
Difficult to Read SecHub HMTL Report - WebScan: Netsparker

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#447]
Netsparker returns finding descriptions in HTML. The SecHub Report in HMTL format will show the HTML output as text, therefore the report is difficult to read.

![netsparker_output_html](https://user-images.githubusercontent.com/2007739/98858052-43547180-2460-11eb-8469-bca1151fbfc9.png)

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
We have agreed to convert Netsparker HTML to a simple asciidoc variant, means:

- paragraphs are replaced by space
- tables are converted to asciidoc style
- lists are converted as well
- links are handled

At this time these are the only mentioned 4 HTML elements used by netsparker and the converter does only handle those.
