### ISSUE TITLE
Webscan max scan duration

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#455]
Webscans can take a very long time. They can take from minutes, to hours, to days. One should be able to set a max scan duration as parameter for every job.

~~~
{
    "apiVersion": "1.0",
    "webScan": {
        "uris": [
            "https://productfailure.demo.example.org"
        ],
        maxScanDuration: "1"
    }
}
~~~

Netsparker already has a parameter to set the max scan duration. By default Netsparker sets the max scan duration to 48 hours. The minimum is 1 hour.

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
Good idea. I would appreciate to use here time unit object also as described at 
https://github.com/Daimler/sechub/issues/440#issuecomment-728994530

**Comment by de-jcup** [comment]
We support `millisecond`, `second`, `minute`, `hour`

Here a final result example (using `hour`)

```json
{
    "apiVersion": "1.0",
    "webScan": {
        "uris": [
            "https://productfailure.demo.example.org"
        ],
        "maxScanDuration": {
			"duration" : 1,
			"unit" : "hour"
		}
    }
}
```
