### ISSUE TITLE
Code flow in HTML Report

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#459]
The SecHub Report in JSON format contains the code flow from the source to the sink with all intermediate steps. However, the HTML report contains only the source and sink, but not the intermediate steps. As a consequence, one needs to look at both reports to understand the issue. Both the HTML report and the SecHub Report should contain the same information.

The code flow in the HTML Report could look as shown in the mockup (below). Fully expanded the code flow will start with the sink as first row, the intermediate steps in the following rows, until the sink which is the last row.

![sechub-report-item-open](https://user-images.githubusercontent.com/2007739/99373826-2ab1e480-28c2-11eb-8111-2d5e06ce6595.png)

The non expanded code flow section is shown as mockup (below). 
![sechub-report-item-closed](https://user-images.githubusercontent.com/2007739/99373823-2a194e00-28c2-11eb-92ac-75ffd205eb4c.png)

Expanding the code flow should happen with Cascading Stylesheet (CSS) only, to avoid the use of JavaScript.

---
<sup>Jeremias Eppler <jeremias.eppler@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
@4w31ss3 Thanx, looks really nice:

**Default (no opened callstack):**
![image](https://user-images.githubusercontent.com/11644753/105993817-18fd7200-60a7-11eb-833c-4dfa2e43c7a7.png)

**Opened callstack variant:**
![image](https://user-images.githubusercontent.com/11644753/105993882-2ca8d880-60a7-11eb-9f3e-6dbee5cd838f.png)
