### ISSUE TITLE
Release Assets: Provide asset for each OS platform on its own

### ISSUE THREAD

**Issue by romahnp** [Daimler/sechub#468]
At the moment, each Release Asset contains the executables for all OS platforms in one archive. But in most cases only one of these artefacts is required. For example when building a docker image only Linux-386 is required.

We suggest the following solution:
- Create an release asset for each OS platform

As you can see in the following screenshot, distributing all artefacts in one ZIP causes a lot of overhead when building a docker image:

![image](https://user-images.githubusercontent.com/25765877/100334108-a3582580-2fd3-11eb-9b54-beb1333b2e1e.png)

**Comment by sven-dmlr** [comment]
Hello @romahnp,
thanks for posting the idea.
I just figured out that there is already an issue for this: #394 
Please follow this to see the progress there.

I will close this issue as a duplicate.

Best regards, Sven

---
<sup>Sven Dolderer <sven.dolderer@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>
