### ISSUE TITLE
Project description must be changeable and shall appear in project detail JSON

### ISSUE THREAD

**Issue by sven-dmlr** [Daimler/sechub#558]
## Situation
- Currently we cannot change a description for a project
- The project description does also not appear inside the project detail JSON 
  (see https://daimler.github.io/sechub/latest/sechub-restapi.html#section-usecase-UC_021)

## Wanted
As an administrator I want to
- change the description for a project
- see description when I fetch project details

## Solution
- New REST endpoint to update description
- Enhance details 

related to: #332

**Comment by de-jcup** [comment]
Duplicate of https://github.com/Daimler/sechub/issues/97

**Comment by sven-dmlr** [comment]
Thanks for the hint.
It's only partly duplicate.

**Comment by de-jcup** [comment]
@sven-dmlr  I updated the issue so it contains only the comment part. So we can work parallel on #97 and this one
