### ISSUE TITLE
Assign user to project should respond with HTTPStatus.OK instead of CREATED

### ISSUE THREAD

**Issue by 4w31ss3** [Daimler/sechub#567]
# Situation
Currently, on a POST request to `project/{projectId}/membership/{userId}` the response status is CREATED.

# Wanted
The response status should be OK, because from API-user perspective no new resource is created but only already existing resources (project-memberships, user) are altered.

# Solution
Change the status code to OK. Don't forget to adjust tests and documentation.

---
<sup>Albert Weißert <albert.weissert@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by de-jcup** [comment]
Just a remark: When we do this, we must ensure the SecHub client written in go handles this correctly.
Normally we should have integration tests using the client (withSecHubClient()) and doing the operation. If not, we should add one so it's ensured the client handles the operation still correctly (and does not complain about wrong status etc.)

**Comment by de-jcup** [comment]
I have checked following:
- [x] Inside review I experienced that the `go client` does not have a assign user command. So no problems here.
- [x] inside developer tools: `sechub-api.sh` does also have not implemented the REST call. So also no problems here.
- [x] Also checked `DeveloperAdministration.java` - there is only POST done without special status code checks - so no problems here as well.
