### ISSUE TITLE
Documentation versions of Client and PDS wrong after release

### ISSUE THREAD

**Issue by 4w31ss3** [Daimler/sechub#585]
# Situation
After building a release only for sechub server, the version of Client and PDS documentation are wrong.

PDS gets the version of sechub server, which is wrong in this case.

https://daimler.github.io/sechub/latest/sechub-product-delegation-server.html
![image](https://user-images.githubusercontent.com/71753812/112462629-910fad80-8d61-11eb-8c40-ecd445cb4075.png)

Client gets the version 0.0.0, which is also not the "latest" version for the client.

https://daimler.github.io/sechub/latest/sechub-client.html
![image](https://user-images.githubusercontent.com/71753812/112462785-bf8d8880-8d61-11eb-9b21-f5416ab8dd0b.png)

# Wanted
Client and PDS should be documented with their latest version. This is not always corresponding to SecHub Server version, because this parts can be release independently.

---
<sup>Albert Weißert <albert.weissert@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by Jeeppler** [comment]
Cross-checked the documentation again. Result, the issue is fixed.
