### ISSUE TITLE
Fix Hikari-Pool "Connection is not available, request timed out after 30000ms"

### ISSUE THREAD

**Issue by 4w31ss3** [Daimler/sechub#594]
## Situation
Sometimes scan jobs are changed to running state but not stored properly and also not passed to Checkmarx for code scan. In this situation we see logs with `HikariPool` `Connection is not available, request timed out after 30000ms.` messages.

This way the corresponding job becomes a "zombie": it has state "RUNNING" but was never passed to Checkmarx and will not be removed from queue.

## Solution
Within our `ScanJobExecutor` class in the `execute` method we catch the exception and call `handleErrors` but don't make sure to cancel the affected job. We should try to cancel the corresponding job, or attempt a retry.

**Comment by de-jcup** [comment]
The Hikari database connection pool problem was fixed with #701 by avoiding blocking dabase transactions via spring batch job operation. The problem no longer exists - so closing this issue.
