### ISSUE TITLE
ScanService does not limit amount of concurrent scans

### ISSUE THREAD

**Issue by 4w31ss3** [Daimler/sechub#598]
## Situation

The `ScanService` class does not limit the amount of concurrent scans. Every `START_SCAN` message received creates  a `ScanJobExecutor` with corresponding background `Thread`. All those threads capture a database connection (over injected `scanService` object). This can easily exceed the default database connection limit. The Hikari.Pool default max connection limit is  **ten** per SecHub server instance. The overall connection limit of our PostgreSQL server is **100**.

## Problem

While the connection pool maximum is exceeded requests to the server can often be denied with `HTTP 401`, because other RestControllers can't validate credentials without an accessible database connection. Bursts of high amounts of scan requests can therefore compromise the user experience of SecHub server.

## Solution

`ScanService` should limit the amount of concurrent running threads and therefore scans. This could be done by creating a queue of such scan requests.

**Comment by de-jcup** [comment]
The Hikari database connection pool problem was fixed with #701 by avoiding blocking dabase transactions via spring batch job operation. The problem no longer exists - so closing this issue.
