### ISSUE TITLE
Upgrade SpringBoot to version 2.5

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#609]
The objective of SecHub is to stay up to date with SpringBoot releases.

- SpringBoot version 2.5 is currently in preview: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5.0-RC1-Release-Notes
- SpringBoot 2.5 will add support for Java 16: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.5.0-M1-Release-Notes#java-16-support

**Comment by Jeeppler** [comment]
Spring Boot 2.5 should be released on the: May 20 2021: https://spring.io/blog/2021/04/15/spring-boot-2-5-0-rc1-available-now

**Comment by Jeeppler** [comment]
Spring Boot 2.5 is GA: https://spring.io/blog/2021/05/20/spring-boot-2-5-is-now-ga

**Comment by de-jcup** [comment]
Current version is now 2.5.2 see https://spring.io/projects/spring-boot

**Comment by de-jcup** [comment]
When switching to spring boot 2.5.2 we have following error message inside our gradle build:

> Failed to apply plugin 'org.springframework.boot'.
   > Spring Boot plugin requires Gradle 6.8.x, 6.9.x, or 7.x. The current version is Gradle 6.7.1

So we will upgrade to gradle version 6.9 - The necessary steps to upgrade to 7.0 as mentioned in #495 does take more time and must  not be done inside this issue.
