### ISSUE TITLE
Disable TLS 1.1 and TLS 1.2

### ISSUE THREAD

**Issue by company-jcup** [Daimler/sechub#624]
We want to disable TLS 1.0 and TLS 1.1 for security reasons

Links:
- https://stackoverflow.com/questions/38302683/how-can-i-disable-tlsv1-0-with-spring-boot-and-embedded-tomcat
- https://www.baeldung.com/spring-tls-setup

**Comment by de-jcup** [comment]
### Howto check?

### Check TLS version per command line:
#### No longer wanted
openssl s_client -connect localhost:8443 -tls1
openssl s_client -connect localhost:8443 -tls1_1

#### Still wanted
openssl s_client -connect localhost:8443 -tls1_2
openssl s_client -connect localhost:8443 -tls1_3
