### ISSUE TITLE
Disable SHA1 possiblities for TLS 1.2

### ISSUE THREAD

**Issue by company-jcup** [Daimler/sechub#625]
We want to disable the possiblity to use SHA1 in TLS 1.2 (TLS 1.3 does not support it any longer).

_This should be possible by changing spring boot configuration_

We will setup dedicated ciphers for
- SecHub Server
- PDS

**Comment by de-jcup** [comment]
At 
https://security.stackexchange.com/questions/120347/how-to-disable-weak-cipher-suits-in-java-application-server-for-ssl
they propose to use at JDK 
```
jdk.tls.disabledAlgorithms=MD5, SHA1, DSA, RSA keySize < 4096
```

But if we use this, product adpaters would not be able to connect to products where the ciphers are weak (and maybe it is not possible to change this)

So for our `PDS` servers the JDK settings would be okay, but not for SecHub server itself because this would also affect the client communication.

**Comment by de-jcup** [comment]
Reading 
https://docs.spring.io/spring-boot/docs/2.5.0/reference/html/application-properties.html#application-properties.server.server.ssl.ciphers

We can define ciphers by 
```
server.ssl.ciphers
```

Reading https://docs.oracle.com/javase/8/docs/api/javax/crypto/Cipher.html
Every Java 8 must support:

```
    AES/CBC/NoPadding (128)
    AES/CBC/PKCS5Padding (128)
    AES/ECB/NoPadding (128)
    AES/ECB/PKCS5Padding (128)
    DES/CBC/NoPadding (56)
    DES/CBC/PKCS5Padding (56)
    DES/ECB/NoPadding (56)
    DES/ECB/PKCS5Padding (56)
    DESede/CBC/NoPadding (168)
    DESede/CBC/PKCS5Padding (168)
    DESede/ECB/NoPadding (168)
    DESede/ECB/PKCS5Padding (168)
    RSA/ECB/PKCS1Padding (1024, 2048)
    RSA/ECB/OAEPWithSHA-1AndMGF1Padding (1024, 2048)
    RSA/ECB/OAEPWithSHA-256AndMGF1Padding (1024, 2048)
```
Maybe we should restrict t o
```
         TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
         TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
         TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
         TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
         TLS_DHE_DSS_WITH_AES_128_GCM_SHA256
         TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
         TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
         TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
         TLS_AES_128_GCM_SHA256
         TLS_AES_256_GCM_SHA384
         TLS_AES_128_CCM_SHA256

```

**Comment by Jeeppler** [comment]
[DES](https://en.wikipedia.org/wiki/Data_Encryption_Standard) and AES in [ECB](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_codebook_(ECB)) mode are is not secure.

[DSS](https://en.wikipedia.org/wiki/Digital_Signature_Algorithm) is only supported by Java. However, browsers do not support it (https://security.stackexchange.com/questions/84311/dhe-dss-vs-dhe-rsa). As a result, DHE_DSS can be disabled.

Those are secure choices: 

```
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
TLS_AES_128_GCM_SHA256
TLS_AES_256_GCM_SHA384
TLS_AES_128_CCM_SHA256
```

In addition, TLS 1.3 introduced a new stream cipher based on a combination of [ChaCha20](https://en.wikipedia.org/wiki/Salsa20#ChaCha_variant) and [Poly1305](https://en.wikipedia.org/wiki/Poly1305). For further information have a loot at: https://www.cloudinsidr.com/content/tls-1-3-and-tls-1-2-cipher-suites-demystified-how-to-pick-your-ciphers-wisely/
