### ISSUE TITLE
PDS throws NPE when nothing uploaded, and unzipUploads set to default or true

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#627]
## Situation

- Start a PDS where unzipUploads not set, is not defined or true (configuration).
- Start new PDS job
- Mark job as ready to start

## Output

We have NPE at server console (in Eclipse).

**Comment by de-jcup** [comment]
This was a follow up issue from #626 

```java
// inside PDSExecutionCallable.java

File workspaceFolder = workspaceService.getWorkspaceFolder(jobUUID);
builder.environment().put("PDS_JOB_WORKSPACE_LOCATION", workspaceFolder.toPath().toRealPath().toString());
     
```
The NPE happend inside the second line.
