### ISSUE TITLE
SARIF: Support taxonomy in SARIF reports so CWE is available

### ISSUE THREAD

**Issue by company-jcup** [Daimler/sechub#628]
## Situation
At the moment SARIF imports do not handle taxonomy data.

## Wanted
A SARIF report result with CWE inside shall be visible inside SecHub report result

## Solution
- Improve SeReCo Import for SARIF
- Write tests

**Comment by Jeeppler** [comment]
Starting from [GoSec version 2.8](https://github.com/securego/gosec/releases/tag/v2.8.0), GoSec supports the CWE taxonomy.

For details have a look at: https://github.com/securego/gosec/pull/602

**Comment by de-jcup** [comment]
NOTE: Sarif validation from microsoft can be used to check for valid sarif example files with taxonomy
https://sarifweb.azurewebsites.net/Validation
