### ISSUE TITLE
Provide error and system out data inside PDSJob data in database + Rest access

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#643]
# Usecases

## Admin wants to get error stream data per REST API for PDS job
As an administrator I can fetch the error stream output for a PDS job which has been run.
The admin knows the PDS job UUID

## Admin wants to get output stream data per REST API for PDS job
As an administrator I can fetch the out stream output for a PDS job which has been run.
The admin knows the PDS job UUID

# Technical details
- We need to add two additional text fields to PDSJob entity
- We do not change the existing admin rest call which can fetch result or error. this will be done in another issue!

**Comment by Jeeppler** [comment]
The endpoint could be something like `job/<job-uuid>/output-stream`.

**Comment by de-jcup** [comment]
We could have two calls 
- `job/<job-uuid>/output-stream`
- `job/<job-uuid>/error-stream`

**Comment by company-jcup** [comment]
Another option would be 
`job/<job-uuid>/stream/output`
`job/<job-uuid>/stream/error`

We must handle following two variants:

1. Job is still running
- REST services will fetch directly the output files from current workspace

2. Job has been done/failed
- REST services will fetch data from database

**Comment by de-jcup** [comment]
The mechanism to provide this in a clustered environment is a little bit tricky - here the used  approach (will be available in documentation as well):
![overview-pds-fetch-stream-content](https://user-images.githubusercontent.com/11644753/133399978-d3e63509-64ac-40df-8c5d-791c2097f635.png)
