### ISSUE TITLE
Duplicate entries in admin job list

### ISSUE THREAD

**Issue by sven-dmlr** [Daimler/sechub#654]
# Problem
It can happen that the admin job list contains the same job twice or more.

This causes problems e.g. when the job shall be cancelled, you get an exception that the SQL query returns more than one row.

# How to reproduce

1. You have a job in state 'RUNNING'. E.g. one that has no result from the backend after a long time.
2. In the Admin-UI: Click Job > "Cancel job" and enter the job's UUID
3. Now list the running jobs: Job > "Show all running batch jobs" and you will find two entries with the same job UUID

**Comment by de-jcup** [comment]
Hm. I know there was an issue. 

But I was not able to reproduce the problem with given instructions. 
I think the problem happens only when it comes to data pool connection timeouts (see #594 ) which lead to illegal states.

And inside `V1__initial_version.sql` we got
```sql
ALTER TABLE adm_job_information ADD CONSTRAINT c05_adm_job_information_jobuuid unique (job_uuid);
```
So the ID is UUID for the job information but the field job_uuid is also unique, so we should never have duplicated entries.

**Comment by sven-dmlr** [comment]
@de-jcup Thanks for investigating.

Ok. I close this issue.
We'll open a new one in case the problem reoccurs.
