### ISSUE TITLE
Change transaction handling on scanning to avoid running out DB datapool connections

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#701]
## Situation
We have often problems with database datapool connections (Hikari Pool problems). 
One of the follow up problems is, that the running state of some SecHub jobs is not updated correctly!

So we got sometimes "Zombie" jobs which are still in running state while the executed product has still finished the scan

So admins need to restart the job which will fetch the results from product and handle the running state again. 

## Wanted
We do not want to have such problems at all - there should be no problems with database transaction pooling.

### Hypothese 1: Scan service transaction handling 
The scan service does currently uses "normal" spring boot transaction handling - so when the service has been called, the transaction will be used as long as the service call does not return the result.

### Hypothese 2: Spring Boot Batch framework
Another idea would be that spring boot batch does block transactions while "spring batch job" is running.
(But this is not so realistic)

## Solution
We concentrate on Hyptheses 1 and use no longer Spring Boot standard transaction handling but instead use the entity manager from `JPA` directly and do only very short transaction handling inside scan thread.

**Comment by sven-dmlr** [comment]
For Postgres, you can checlk the used connections, you can use this snippet to get a live view of the used connections
```
watch -n 10 "psql -c \"select count(*),client_addr from pg_stat_activity where application_name like '%JDBC Driver' group by client_addr order by client_addr;\""
```

**Comment by de-jcup** [comment]
Hmm... `ScanExecutionTasklet.java` executeSafe() method is running in transaction of Spring Batch job... If we would simply create a new Thread here and directly return `RepeatStatus.FINISHED` this should close the batch job transaction.

All other parts seem to use `@Transactional(propagation = Propagation.REQUIRES_NEW)` and do only short operations - so the transactions will be closed very soon.

**Comment by de-jcup** [comment]
Some additional SQL scripts
- Show all virtualxid entries - means running transactions in PostgreSQL
  `select * from pg_locks pl where pl.locktype like '%virtualxid%'`
  
-  ...

**Comment by de-jcup** [comment]
Because `testcontainer` do always start with IP `0.0.0.0` everybody inside the same network can have access to the database when the default test credentials are used (testcontainer do always have user `test` and password `test`!

There are workarounds possible to mitigate
- local firewalls or
- set default IP from 0.0.0.0 to 127.0.0.1 - see https://forums.docker.com/t/can-i-change-the-default-ip-from-0-0-0-0-when-binding/30358/3
- turn off the `ryuk` sidecar container (but database shutdown would be not so simple)

All of these solutions do not automatically protect a developer who wants to simply test a postgresql connection or are cumbersome workarounds. Hopefully this will be fixed in future inside the `testcontainer` project.

But to prevent security problems when somebody uses this for development and does not think about the situation (so doing no preventions ) we will do following:

- insist on a strong password when password is defined
- create a randomized passsword for integration tests when no password is defined - 
  the password will be available in info files, which will can be used in #716 to setup variables, so generated credentials are known at execution time
- warn inside test container logs about the problem

**Comment by de-jcup** [comment]
Hmm.. i have concerns about the usage of 0.0.0.0 at all. Maybe we should remove `testcontainer` and  support just a docker file with alpine and preconfigured postgres instead by a bash script and call this by the Java wrapper instead. The script will only expose 127.0.0.0:$exposedPort.

So we
- would have a secure solution
- can remove the warning parts in logs
- could easily access/change postgresql configuration
