### ISSUE TITLE
Build sechub-api-java

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#728]
This task is a follow up issue to #377. In task #377, the OpenAPI file generation and OpenAPI Client Source Code generation were improved. However, building and testing were left to this issue.

## Steps

1. Build a "FatJar" from the current generated source code
2. Publish "FatJar" to local maven
3. Import and use the "FatJar" in the SecHub Java Client (sechub-java-client)
4. Run tests to make sure the SecHub Java Client works

## Other tasks

- [ ] Adjust github actions workflow
- [ ] Adjust github actions release workflow
- [ ] Adjust Jenkins file

**Comment by de-jcup** [comment]
Structure:
```
sechub-server (1)
sechub-integrationtest(2)
sechub-doc 
   /gen/openapi.json (3)

sechub-java-client 
  build.java (4a) // starts generation and creates files (4)
  /gen-output-folder/
     /src/main/java/JavaClientAPI.java (4b)
     build.gradle (5a) 
     build/libs/generated.jar (ohne dependencies...)
     /build/libs/sechub-openapi-java-fat.jar (5b) + (6)
  /src/main/java/SecHubClient.java (7) // compile
  /src/test/java/SecHubClientTest.java (7) // compile + test

```

Steps for complete build:
1. Normal build of sechub server without java client
2. Execute integration tests (necessary for input for sechub-doc build)
3. Execute documentation task inside `sechub-doc` will generate `openapi.json`
4. Execute java-client generation - will generate `*.java` files for generated client
   - no java compile
   - no test execution!
5. Switch to generated source folder and execute there the generated `build.gradle` and create a
    fat jar
6. Upload the fat jar to local maven repository (maven publish)
7. Build (compile + test)  `sechub-java-client` with gradle fat jar dependency
8. Create a Fat Jar for `sechub-client-java` , so it can be used as a external library.

**Comment by de-jcup** [comment]
Decision : We will not provide a fat jar!

Reason: When using Software composition analysis tools(SCA) like `dependabot` vulnerabilities inside the used libraries may be not recognized if we would do it by fat jar approach.
Also updates would always include the complete fat jar - even when only a sub library would be updated for security reasons.

Instead we will do a "normal" maven POM approach.
If possible we will also provide the small sechub-client-java (or better: sechub-api-java) inside github packages together with the pom describing the necessary runtime dependencies by this issue.

**Comment by Jeeppler** [comment]
I prefer the name `sechub-api-java`.
