### ISSUE TITLE
Introduce github actions dependabot

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#733]
## Situation
Currently dependencies are manually inspected and also updated on demand 

## Wanted
It would be nice to have an automated inspection with suggestions which parts should be updated

## Solution
We could introduce a [DependaBot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions?learn=dependency_version_updates#about-dependabot-and-github-actions) workflow.

**Comment by Jeeppler** [comment]
@de-jcup have a look at #732.
