### ISSUE TITLE
HTTP 4xx client errors shall have error messages in JSON results

### ISSUE THREAD

**Issue by company-jcup** [Daimler/sechub#734]
## Situation
When a user marks false positives with a wrong finding id, he/she gets a 404 - Not found.
This is okay, but the error message is empty, so the user got no clue why this happens

## Wanted
The thrown `NotFoundException` has got an error message for the user. This message shall be in JSON output returned to user.

## Solution
The error handling has been changed with Spring Boot 2.3.0 - the exception messages are no longer added per default. The implementation was done with an earlier version and the problem was not mentioned.

We must include the errror message inside the json error object:

This can be done via:
```
server.error.include-message = always
```
https://stackoverflow.com/questions/62562258/spring-boot-restcontroller-on-error-status-response-body-message-of-error-is-e

We also add a integration test which checks for such a situation and inspect the json output having the expected message.

**Comment by de-jcup** [comment]
The mentioned solution with `server.error.include-message = always` does not work, we must do this inside `ServerErrorController.java` by ourself.

Here we can also differ between different HTTP status variants.
For 5xx - server errors - we WILL NOT provide the error messages but only for 4xx client errors where the client has a real need to know the exception message.

**Comment by de-jcup** [comment]
This was also changed for PDS as well.
