### ISSUE TITLE
Rename sechub-client-java to sechub-api-java

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#746]
## Situation
We have a sechub client which is written in go.

But we have also the gradle subproject "sechub-client-java" which contains a wrapper and generated java code (open api generator) - it is still ongoing and not complete, but will be available in the near future. With this subproject (and the planned go and typescript variants) we provide an API layer for other tools like IDE plugins or caller plattforms, so they do not need to implement API calls by themselves. 

So when we talk about a "client" it is not clear what is really meant.

## Wanted
It shall be clear what is meant by the word "client" and what is the "api layer" for other tools.

## Solution
1. We use the term `client` only with gradle subproject `sechub-cli` .
2. We rename `sechub-client-java` to `sechub-api-java`
    (+ adopt  includes gradle build, documentation etc.)

Further api layer will also use same name pattern : `sechub-api-$language`

**Comment by Vivek-Prajapatii** [comment]
Hii @de-jcup, may i take this issue? as i'm new to opensource

**Comment by de-jcup** [comment]
@Vivek-Prajapatii : Of course you can. We welcome new contributors!

Please read first
- https://github.com/Daimler/sechub/wiki/Collaboration#cla
- https://github.com/Daimler/sechub/wiki/Collaboration#how-to-create-pull-requests

So the first step is to agree to the Daimler FOSS CLA as mentioned at the links.

After this, make your changes and create a PR as described.

**Comment by de-jcup** [comment]
@Vivek-Prajapatii : Sorry, but I still have not received the CLA approve and I need the rename now urgently because I am currently implementing #728 . So I will assign this to myself.

If you did sign and send the CLA already please tell me. In this case I will try to check why I did not get the response.
