### ISSUE TITLE
Change PDS check period time unit from minutes to milliseconds + introduce new configuration identifiers

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#787]
### Configuration ids for defaults 
While implementing #785 I did not change the configuration identifier. We should change those config identifiers as well - so it's more understandable. Also the next part (change time unit to milliseconds for periodic ceck) should be handled.

### Minutes for period checks are not a good option for PDS
Also it became clear that having a check period only in minutes has a few disadvantages - e.g. Some scanners are extreme fast and do not need minutes to do a check. Also every integration test using a real PDS instance will wait at least 1 minute. And this increases our build times much! 

_Remark: In our special mocked adapters this is not a problem because the time to wait etc. is handled there in a special way. An in the normal product environments to wait minutes is also correct!_

So we needs this for our PDS integration tests only, because here we do not mock the product communication but do really start a product communication etc. 
Additionally  we had often the situation that scans with PDS and some CLI tools  are extreme fast. So we want to be able to setup a dedicated short time  inside those pds executor configurations as well.

### General
- change config identifiers for default values in `PDSSetupInstallImpl` appropriate and change documentation 
- change PDS runtime configuration entry identifier so it is clear the check period is in milliseconds now
- add to abstractAdapterConfigBuilder setTimeToWaitForNextCheckOperationInMilliseconds and use it only by PDS executors - we keep the other executors "as is" (keep stable).
- change the minimum value for checks in milliseconds to 500 ms (if not already done)
- change default value for PDS check time period to 30 seconds
- change integration test application settings to use 500 ms (so our test checks are very fast)

### Identifier changes
- replace  `sechub.adapter.pds.default.scanresultcheck.period.minutes` with `sechub.adapter.pds.default.check.timetowait.milliseconds`
- replace `sechub.adapter.pds.default.scanresultcheck.timeout.minutes` with
  `sechub.adapter.pds.default.timeout.minutes`

**Comment by company-jcup** [comment]
https://teams.e.corpintra.net/teams/modifyperson

da hab ichs angepasst, zieht aber nicht...
