### ISSUE TITLE
Wrong description in `PDSConfigDataKeyProvider.java`

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#868]
Typos in `sechub-commons-pds/src/main/java/com/daimler/sechub/commons/pds/PDSConfigDataKeyProvider.java` 

```
    PDS_SCAN_CONFIGURATION(new ExecutionPDSKey(PDSDefaultParameterKeyConstants.PARAM_KEY_PDS_SCAN_CONFIGURATION,
            "This conains the sechub storage location when sechub storage shall be used. So PDS knows location - in combination with sechub job UUID reuse is possible")
                    .markGenerated().markAsAvailableInsideScript())

    ;
```

and 

```
    PDS_SCAN_TARGET_URL(new ExecutionPDSKey(PDSDefaultParameterKeyConstants.PARAM_KEY_PDS_SCAN_TARGET_URL,
            "This conains the sechub storage location when sechub storage shall be used. So PDS knows location - in combination with sechub job UUID reuse is possible")
                    .markGenerated().markAsAvailableInsideScript())

    ,
```

Both `PDS_SCAN_TARGET_URL` and `PDS_SCAN_CONFIGURATION` are related to web scanning, they have nothing to do with storage.

**Comment by Vivek-Prajapatii** [comment]
I would love to work on it.

**Comment by Jeeppler** [comment]
Yes, sure. 

The fix the issue:

1. fork the SecHub project on GitHub
2. fix the typos
3. create a pull-request

Step 2 in more details:

to fix the typos:

1. Open the file: `sechub-commons-pds/src/main/java/com/daimler/sechub/commons/pds/PDSConfigDataKeyProvider.java` with a text editor or IDE. 
2. Change the texts describing `PDS_SCAN_CONFIGURATION` and `PDS_SCAN_TARGET_URL`. The text should be similar to: https://daimler.github.io/sechub/latest/sechub-product-delegation-server.html#generated-variables

Once you opened the pull-request, mention me, @de-jcup  and @sven-dmlr in the description.

Feel free to ask any other questions you have as part of this issue.

**Comment by Jeeppler** [comment]
@Vivek-Prajapatii congratulations to your first contribution and fixing this issue.

**Comment by Vivek-Prajapatii** [comment]
thank you, @Jeeppler
